#!/usr/bin/env bash
# fs-reorganize — apply an approved manifest.csv as REVERSIBLE file moves.
# Never deletes: junk is quarantined to _REVIEW_DELETE/. Every move is logged and
# an undo.sh is generated. Collisions get a numeric suffix (never overwrite).
#
# Usage: reorganize.sh MANIFEST.csv [--base DIR] [--apply]
#   default is DRY-RUN (prints planned ops, touches nothing); --apply executes.
set -euo pipefail

MANIFEST=""; BASE=""; APPLY=0
while [ $# -gt 0 ]; do
  case "$1" in
    --base) BASE="$2"; shift 2 ;;
    --apply) APPLY=1; shift ;;
    *) MANIFEST="$1"; shift ;;
  esac
done
[ -n "$MANIFEST" ] && [ -f "$MANIFEST" ] || { echo "usage: reorganize.sh MANIFEST.csv [--base DIR] [--apply]" >&2; exit 1; }
[ -n "$BASE" ] || BASE="$(cd "$(dirname "$MANIFEST")" && pwd)"
mkdir -p "$BASE"
BASE="$(cd "$BASE" && pwd)"

APPLY="$APPLY" BASE="$BASE" python3 - "$MANIFEST" <<'PY'
import csv, os, shlex, sys

manifest = sys.argv[1]
base = os.environ["BASE"]
apply = os.environ["APPLY"] == "1"
quarantine_dir = os.path.join(base, "_REVIEW_DELETE")
moves_log = os.path.join(base, "moves.log")
undo_sh = os.path.join(base, "undo.sh")


def unique(dest):
    """Suffix ' (N)' before the extension if dest exists. Never overwrite."""
    if not os.path.exists(dest):
        return dest
    d, name = os.path.split(dest)
    stem, ext = os.path.splitext(name)
    n = 2
    while True:
        cand = os.path.join(d, f"{stem} ({n}){ext}")
        if not os.path.exists(cand):
            return cand
        n += 1


planned = []   # (orig, dest)
with open(manifest, newline="") as fh:
    for row in csv.DictReader(fh):
        action = row["proposed_action"].strip()
        orig = row["current_path"]
        if action == "keep" or not orig:
            continue
        if not os.path.exists(orig):
            print(f"skip (missing): {orig}", file=sys.stderr)
            continue
        if action == "quarantine":
            dest = unique(os.path.join(quarantine_dir, os.path.basename(orig)))
        elif action == "move":
            tp = row["target_path"].strip() or f"{row['category']}/{os.path.basename(orig)}"
            dest = unique(tp if os.path.isabs(tp) else os.path.join(base, tp))
        else:
            print(f"skip (unknown action {action!r}): {orig}", file=sys.stderr)
            continue
        planned.append((orig, dest))

if not apply:
    print(f"DRY-RUN — {len(planned)} planned operations (nothing changed):")
    for orig, dest in planned:
        print(f"  {orig}\n    -> {dest}")
    print("Re-run with --apply to execute.")
    sys.exit(0)

# Crash-safe: append each move to moves.log as it happens (flush+fsync), and
# tolerate per-file errors instead of aborting the whole run. moves.log is the
# source of truth; undo.sh is rebuilt from it at the end.
applied = errors = 0
logfh = open(moves_log, "a")
for orig, dest in planned:
    if not os.path.exists(orig):
        continue  # already moved (resumable) or vanished
    try:
        os.makedirs(os.path.dirname(dest), exist_ok=True)
        os.rename(orig, dest)
        logfh.write(f"{orig}\t{dest}\n")
        logfh.flush()
        os.fsync(logfh.fileno())
        applied += 1
    except OSError as e:
        print(f"ERROR moving {orig} -> {dest}: {e}", file=sys.stderr)
        errors += 1
logfh.close()

# Rebuild undo.sh from the ENTIRE moves.log (covers prior runs too).
pairs = []
with open(moves_log) as fh:
    for line in fh:
        if "\t" in line:
            o, d = line.rstrip("\n").split("\t", 1)
            pairs.append((o, d))
with open(undo_sh, "w") as fh:
    fh.write("#!/usr/bin/env bash\n# Auto-generated by fs-reorganize. Reverses every logged move.\nset -e\n")
    for orig, dest in reversed(pairs):
        fh.write(f"[ -e {shlex.quote(dest)} ] && mkdir -p {shlex.quote(os.path.dirname(orig))} "
                 f"&& mv {shlex.quote(dest)} {shlex.quote(orig)}\n")
os.chmod(undo_sh, 0o755)

print(f"applied {applied} moves ({errors} errors)")
print(f"  log:  {moves_log}  ({len(pairs)} total logged)")
print(f"  undo: {undo_sh}")
PY
