#!/usr/bin/env bash
# fs-reorganize — apply an approved manifest.csv as REVERSIBLE file moves.
# Never deletes: junk is quarantined to _REVIEW_DELETE/. Every move is logged and
# an undo.sh is generated. Collisions get a numeric suffix (never overwrite).
#
# Usage: reorganize.sh MANIFEST.csv [--base DIR] [--apply]
#   default is DRY-RUN (prints planned ops, touches nothing); --apply executes.
set -euo pipefail

MANIFEST=""; BASE=""; APPLY=0
while [ $# -gt 0 ]; do
  case "$1" in
    --base) BASE="$2"; shift 2 ;;
    --apply) APPLY=1; shift ;;
    *) MANIFEST="$1"; shift ;;
  esac
done
[ -n "$MANIFEST" ] && [ -f "$MANIFEST" ] || { echo "usage: reorganize.sh MANIFEST.csv [--base DIR] [--apply]" >&2; exit 1; }
[ -n "$BASE" ] || BASE="$(cd "$(dirname "$MANIFEST")" && pwd)"
BASE="$(cd "$BASE" && pwd)"

APPLY="$APPLY" BASE="$BASE" python3 - "$MANIFEST" <<'PY'
import csv, os, shlex, sys

manifest = sys.argv[1]
base = os.environ["BASE"]
apply = os.environ["APPLY"] == "1"
quarantine_dir = os.path.join(base, "_REVIEW_DELETE")
moves_log = os.path.join(base, "moves.log")
undo_sh = os.path.join(base, "undo.sh")


def unique(dest):
    """Suffix ' (N)' before the extension if dest exists. Never overwrite."""
    if not os.path.exists(dest):
        return dest
    d, name = os.path.split(dest)
    stem, ext = os.path.splitext(name)
    n = 2
    while True:
        cand = os.path.join(d, f"{stem} ({n}){ext}")
        if not os.path.exists(cand):
            return cand
        n += 1


planned = []   # (orig, dest)
with open(manifest, newline="") as fh:
    for row in csv.DictReader(fh):
        action = row["proposed_action"].strip()
        orig = row["current_path"]
        if action == "keep" or not orig:
            continue
        if not os.path.exists(orig):
            print(f"skip (missing): {orig}", file=sys.stderr)
            continue
        if action == "quarantine":
            dest = unique(os.path.join(quarantine_dir, os.path.basename(orig)))
        elif action == "move":
            tp = row["target_path"].strip() or f"{row['category']}/{os.path.basename(orig)}"
            dest = unique(tp if os.path.isabs(tp) else os.path.join(base, tp))
        else:
            print(f"skip (unknown action {action!r}): {orig}", file=sys.stderr)
            continue
        planned.append((orig, dest))

if not apply:
    print(f"DRY-RUN — {len(planned)} planned operations (nothing changed):")
    for orig, dest in planned:
        print(f"  {orig}\n    -> {dest}")
    print("Re-run with --apply to execute.")
    sys.exit(0)

done = []
for orig, dest in planned:
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    os.rename(orig, dest)
    done.append((orig, dest))

with open(moves_log, "a") as fh:
    for orig, dest in done:
        fh.write(f"{orig}\t{dest}\n")

# Generate undo.sh: reverse every move in reverse order. Idempotent-safe guards.
with open(undo_sh, "w") as fh:
    fh.write("#!/usr/bin/env bash\n# Auto-generated by fs-reorganize. Reverses the moves it applied.\nset -e\n")
    for orig, dest in reversed(done):
        fh.write(f"[ -e {shlex.quote(dest)} ] && mkdir -p {shlex.quote(os.path.dirname(orig))} "
                 f"&& mv {shlex.quote(dest)} {shlex.quote(orig)}\n")
os.chmod(undo_sh, 0o755)

print(f"applied {len(done)} moves")
print(f"  log:  {moves_log}")
print(f"  undo: {undo_sh}")
PY
